name: CI - Paper-trade smoke (weekly)

on:
  schedule:
    - cron: '0 6 * * 1'  # weekly on Monday 06:00 UTC
  workflow_dispatch:
    inputs:
      allow_notifications:
        description: 'Allow remote notifications (requires repo secret ALLOW_NOTIFICATIONS=1)'
        required: false
        default: 'false'

jobs:
  run-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run paper-trade simulator
        run: |
          python scripts/trading/paper_trading_sim.py --dataset data/dataset_SMOKE.parquet --output outputs/paper_trade_report.json

      - name: Extract metrics
        run: |
          python scripts/qa/extract_paper_trade_metrics.py --input outputs/paper_trade_report.json --output outputs/paper_trade_metrics.json

      - name: Compare metrics to baseline
        run: |
          python scripts/qa/compare_metrics_to_baseline.py --metrics '{"final_net": 0.05, "max_drawdown": 0.10}'

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: paper-trade-smoke-artifacts
          path: |
            outputs/paper_trade_report.json
            outputs/paper_trade_report_trades.csv
            outputs/paper_trade_metrics.json

      - name: optional-run-notifier
        if: ${{ github.event.inputs.allow_notifications == 'true' }}
        env:
          ALLOW_NOTIFICATIONS: ${{ secrets.ALLOW_NOTIFICATIONS }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${ALLOW_NOTIFICATIONS}" != "1" ]; then
            echo "ALLOW_NOTIFICATIONS not set to 1; skipping remote notifier"
            exit 0
          fi
          echo "Running notifier in guarded mode (will still use --dry-run by default unless explicitly changed)"
          # Default to dry-run to avoid accidental posts; maintainers may edit this step to remove --dry-run
          python scripts/qa/notify_guardrail_failure.py --artifact outputs/paper_trade_metrics.json --enable-issues --enable-slack --dry-run
