name: detect-secrets (weekly)

on:
  schedule:
    - cron: '0 3 * * 1'  # every Monday at 03:00 UTC

jobs:
  detect-secrets-weekly:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install detect-secrets
        run: python -m pip install detect-secrets==1.4.0
      - name: Run detect-secrets
        run: |
          python -m pip install detect-secrets==1.4.0
          chmod +x scripts/ci/run_detect_secrets.sh
          # run but do not fail the workflow immediately; we will inspect output and create an issue if needed
          ./scripts/ci/run_detect_secrets.sh || true

      - name: Check detect-secrets output
        id: check
        run: |
          chmod +x scripts/ci/check_detect_output.sh
          ./scripts/ci/check_detect_output.sh

      - name: Create issue if secrets found
        if: steps.check.outputs.found == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const r = JSON.parse(fs.readFileSync('/tmp/detect_output.json'));
            let body = 'Automated detect-secrets scan found potential secrets in the repository. Please review the baseline and the findings below.\n\n';
            body += 'Findings summary:\n';
            for (const [file, entries] of Object.entries(r.results)) {
              if (entries.length > 0) body += `- ${file}: ${entries.length} potential secrets\n`;
            }
            await github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Security: detect-secrets found potential secrets (automated)',
              body,
            });
