name: detect-secrets (strict)

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install detect-secrets
        run: python -m pip install detect-secrets==1.4.0
      - name: Run detect-secrets (baseline-aware)
        run: |
          python -m pip install detect-secrets==1.4.0
          chmod +x scripts/ci/run_detect_secrets.sh
          ./scripts/ci/run_detect_secrets.sh
