name: Propose baseline PR

on:
  workflow_dispatch:
    inputs:
      allow_push:
        description: 'If true, attempt to push and create PR (must set ALLOW_NOTIFICATIONS=1 secret)'
        required: false
        default: 'false'

jobs:
  propose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt || true

      - name: Run paper-trade smoke
        run: |
          python3 scripts/trading/paper_trading_sim.py --dataset data/dataset_SMOKE.parquet --output outputs/paper_trade_report.json

      - name: Extract metrics
        run: |
          python3 scripts/qa/extract_paper_trade_metrics.py --input outputs/paper_trade_report.json --output outputs/paper_trade_metrics.json

      - name: Compare to baseline
        run: |
          python3 scripts/qa/compare_metrics_to_baseline.py --metrics '{"final_net":0.05,"max_drawdown":0.10}' || true

      - name: Check for baseline improvement
        run: |
          python3 scripts/qa/check_for_baseline_improvement.py --metrics '{"final_net": 0.01}'

      - name: Propose baseline PR (dry-run by default)
        if: ${{ success() }}
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ALLOW_NOTIFICATIONS: ${{ secrets.ALLOW_NOTIFICATIONS }}
        run: |
          if [ "${{ github.event.inputs.allow_push }}" = "true" ]; then
            python3 scripts/qa/create_baseline_pr.py --allow-push
          else
            python3 scripts/qa/create_baseline_pr.py
          fi
