name: Workflow lint + Smoke dry-run

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  lint-yaml:
    name: Lint workflow YAML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install yamllint
        run: |
          python -m pip install --upgrade pip
          pip install yamllint

      - name: Run yamllint
        run: |
          yamllint -c /dev/null .github/workflows || true

  smoke-dryrun:
    name: Smoke dry-run (non-blocking)
    runs-on: ubuntu-latest
    needs: lint-yaml
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install minimal deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run data ingest tests
        run: |
          # Run only the ingest-related tests early to fail fast
          python -m pytest -q tests/test_data_ingest.py

      - name: Generate smoke dataset (dry-run)
        run: |
          python3 scripts/qa/generate_smoke_dataset.py --path data/dataset_SMOKE.parquet --start 2024-01-01 --end 2024-01-03 || true

      - name: Run paper trading sim (dry-run)
        run: |
          # non-destructive: use create_pr=false semantics; write outputs for inspection
          python3 scripts/trading/paper_trading_sim.py --dataset data/dataset_SMOKE.parquet --output outputs/paper_trade_report.json || true

      - name: Extract metrics (dry-run)
        run: |
          python3 scripts/qa/extract_paper_trade_metrics.py --input outputs/paper_trade_report.json --output outputs/paper_trade_metrics.json || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: smoke-artifacts
          path: |
            outputs/paper_trade_report.json
            outputs/paper_trade_metrics.json
            data/dataset_SMOKE.parquet
